"""Add AI analysis fields to Log model

Revision ID: 62594a6c5175
Revises: 62c984d89076
Create Date: 2026-01-26 22:35:24.524403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62594a6c5175'
down_revision = '62c984d89076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_history', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'match_rules', ['rule_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['operator_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['unblock_operator_id'], ['id'])

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_attack_type', sa.String(length=50), nullable=True, comment='AI识别的攻击类型'))
        batch_op.add_column(sa.Column('ai_confidence', sa.Float(), nullable=True, comment='AI识别置信度'))
        batch_op.add_column(sa.Column('ai_analysis_result', sa.Text(), nullable=True, comment='AI完整分析结果'))
        batch_op.create_foreign_key(None, 'honeypots', ['honeypot_id'], ['id'])

    with op.batch_alter_table('match_rules', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_rules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ai_analysis_result')
        batch_op.drop_column('ai_confidence')
        batch_op.drop_column('ai_attack_type')

    with op.batch_alter_table('block_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
