"""初始化数据库表结构

Revision ID: 62c984d89076
Revises: 
Create Date: 2026-01-14 16:13:00.564465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62c984d89076'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('malicious_logs')
    with op.batch_alter_table('block_history', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['unblock_operator_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['operator_id'], ['id'])
        batch_op.create_foreign_key(None, 'match_rules', ['rule_id'], ['id'])

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_log', sa.Text(), nullable=False, comment='原始日志内容'))
        batch_op.add_column(sa.Column('source_ip', sa.String(length=15), nullable=True, comment='源IP地址'))
        batch_op.add_column(sa.Column('target_ip', sa.String(length=15), nullable=True, comment='目标IP地址'))
        batch_op.add_column(sa.Column('source_port', sa.Integer(), nullable=True, comment='源端口'))
        batch_op.add_column(sa.Column('target_port', sa.Integer(), nullable=True, comment='目标端口'))
        batch_op.add_column(sa.Column('protocol', sa.String(length=10), nullable=True, comment='协议类型'))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=255), nullable=True, comment='用户代理'))
        batch_op.add_column(sa.Column('request_path', sa.String(length=255), nullable=True, comment='请求路径'))
        batch_op.add_column(sa.Column('attack_description', sa.Text(), nullable=True, comment='攻击描述'))
        batch_op.add_column(sa.Column('payload', sa.Text(), nullable=True, comment='攻击载荷'))
        batch_op.add_column(sa.Column('is_malicious', sa.Boolean(), nullable=False, comment='是否为恶意流量'))
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=False, comment='是否已阻断'))
        batch_op.add_column(sa.Column('blocked_time', sa.DateTime(), nullable=True, comment='阻断时间'))
        batch_op.alter_column('attack_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_comment='攻击类型')
        batch_op.alter_column('threat_level',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               existing_comment='威胁等级')
        batch_op.alter_column('notes',
               existing_type=mysql.TEXT(),
               comment='备注',
               existing_comment='备注信息',
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'honeypots', ['honeypot_id'], ['id'])
        batch_op.drop_column('processed_time')
        batch_op.drop_column('is_processed')
        batch_op.drop_column('processed_by')
        batch_op.drop_column('details')

    with op.batch_alter_table('match_rules', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_rules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', mysql.TEXT(), nullable=True, comment='攻击详情'))
        batch_op.add_column(sa.Column('processed_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='处理人ID'))
        batch_op.add_column(sa.Column('is_processed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否已处理'))
        batch_op.add_column(sa.Column('processed_time', mysql.DATETIME(), nullable=True, comment='处理时间'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('notes',
               existing_type=mysql.TEXT(),
               comment='备注信息',
               existing_comment='备注',
               existing_nullable=True)
        batch_op.alter_column('threat_level',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False,
               existing_comment='威胁等级')
        batch_op.alter_column('attack_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_comment='攻击类型')
        batch_op.drop_column('blocked_time')
        batch_op.drop_column('is_blocked')
        batch_op.drop_column('is_malicious')
        batch_op.drop_column('payload')
        batch_op.drop_column('attack_description')
        batch_op.drop_column('request_path')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('protocol')
        batch_op.drop_column('target_port')
        batch_op.drop_column('source_port')
        batch_op.drop_column('target_ip')
        batch_op.drop_column('source_ip')
        batch_op.drop_column('raw_log')

    with op.batch_alter_table('block_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('malicious_logs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='恶意日志ID'),
    sa.Column('malicious_ip', mysql.VARCHAR(length=15), nullable=False, comment='恶意IP地址'),
    sa.Column('attack_time', mysql.DATETIME(), nullable=False, comment='攻击时间'),
    sa.Column('raw_log', mysql.TEXT(), nullable=False, comment='原始攻击日志'),
    sa.Column('attack_type', mysql.VARCHAR(length=50), nullable=True, comment='攻击类型'),
    sa.Column('attack_description', mysql.TEXT(), nullable=True, comment='攻击描述'),
    sa.Column('target_service', mysql.VARCHAR(length=50), nullable=True, comment='目标服务/端口'),
    sa.Column('payload', mysql.TEXT(), nullable=True, comment='攻击载荷'),
    sa.Column('threat_level', mysql.VARCHAR(length=20), nullable=False, comment='威胁等级'),
    sa.Column('honeypot_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='来源蜜罐ID'),
    sa.Column('is_blocked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否已阻断'),
    sa.Column('blocked_time', mysql.DATETIME(), nullable=True, comment='阻断时间'),
    sa.Column('notes', mysql.TEXT(), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###
