"""add_is_auto_block_to_ai_config

Revision ID: a666cedf82d4
Revises: dbfe36fa445c
Create Date: 2026-02-24 16:52:49.361044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a666cedf82d4'
down_revision = 'dbfe36fa445c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_auto_block', sa.Boolean(), nullable=False, comment='是否启用自动封禁'))

    with op.batch_alter_table('block_history', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'match_rules', ['rule_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['unblock_operator_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['operator_id'], ['id'])

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'honeypots', ['honeypot_id'], ['id'])

    with op.batch_alter_table('match_rules', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='更新时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('user_infos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_infos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='更新时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('match_rules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('block_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ai_configs', schema=None) as batch_op:
        batch_op.drop_column('is_auto_block')

    # ### end Alembic commands ###
