"""Add AIConfig table

Revision ID: dbfe36fa445c
Revises: 62594a6c5175
Create Date: 2026-01-29 21:20:51.807209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbfe36fa445c'
down_revision = '62594a6c5175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='配置ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='配置名称'),
    sa.Column('api_url', sa.String(length=255), nullable=False, comment='API地址'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='模型名称'),
    sa.Column('api_key', sa.String(length=255), nullable=True, comment='API密钥'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='提供商'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('block_history', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['operator_id'], ['id'])
        batch_op.create_foreign_key(None, 'match_rules', ['rule_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['unblock_operator_id'], ['id'])

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'honeypots', ['honeypot_id'], ['id'])

    with op.batch_alter_table('match_rules', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_rules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('block_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('ai_configs')
    # ### end Alembic commands ###
