"""add_ai_model_name

Revision ID: e3a37730dc6b
Revises: a666cedf82d4
Create Date: 2026-02-25 00:57:40.436897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a37730dc6b'
down_revision = 'a666cedf82d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_history', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['unblock_operator_id'], ['id'])
        batch_op.create_foreign_key(None, 'match_rules', ['rule_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['operator_id'], ['id'])

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_model_name', sa.String(length=100), nullable=True, comment='AI模型名称'))
        batch_op.create_foreign_key(None, 'honeypots', ['honeypot_id'], ['id'])

    with op.batch_alter_table('match_rules', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    with op.batch_alter_table('user_infos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_infos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('match_rules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ai_model_name')

    with op.batch_alter_table('block_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
