"""add failed_login_attempts and locked_until to users

Revision ID: f92a31e3b941
Revises: f1a2b3c4d5e6
Create Date: 2026-04-12 15:19:24.061989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f92a31e3b941'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_history', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['operator_id'], ['id'])
        batch_op.create_foreign_key(None, 'match_rules', ['rule_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['unblock_operator_id'], ['id'])

    with op.batch_alter_table('honeypots', schema=None) as batch_op:
        batch_op.alter_column('pid',
               existing_type=mysql.INTEGER(display_width=11),
               comment='蜜罐子进程PID',
               existing_comment='蜜罐子进程PID，用于重启后判断进程是否仍在运行',
               existing_nullable=True)

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'honeypots', ['honeypot_id'], ['id'])

    with op.batch_alter_table('match_rules', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    with op.batch_alter_table('user_infos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_modules', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'modules', ['module_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True, comment='连续登录失败次数'))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True, comment='账户锁定截止时间'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')

    with op.batch_alter_table('user_modules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('user_infos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('match_rules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('honeypots', schema=None) as batch_op:
        batch_op.alter_column('pid',
               existing_type=mysql.INTEGER(display_width=11),
               comment='蜜罐子进程PID，用于重启后判断进程是否仍在运行',
               existing_comment='蜜罐子进程PID',
               existing_nullable=True)

    with op.batch_alter_table('block_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
